# Generated by Django 4.2.2 on 2023-06-22 19:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="datetime",
        ),
        migrations.AddField(
            model_name="todo",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
