# Generated by Django 4.2.2 on 2023-06-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_remove_todo_datetime_todo_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="todo",
            name="content",
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name="todo",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="todo",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name="todo",
            name="tag",
        ),
        migrations.AddField(
            model_name="todo",
            name="tag",
            field=models.ManyToManyField(related_name="tasks", to="tasks.tag"),
        ),
    ]
